### ISSUE TITLE
glyphicon for feedback

### ISSUE THREAD

**Issue by burkeker** [gbif/portal16#295] opened 2017-02-27 09:40 UTC
The current glyphicon for feedback uses bootstrap "comment", which is being used by many websites to link to "chat" or "message" section/feature. This is somehow misleading. I'd suggest for feedback we should use bullhorn instead.

**Comment by kbraak** [comment] 2017-02-27 10:20
I believe this is a duplicate of https://github.com/gbif/portal16/issues/262. Please add your comments there :)

**Closed by kbraak** 2017-02-27 10:20 UTC
Labels: cost low, duplicate
