### ISSUE TITLE
Pagination of GBIF network search results

### ISSUE THREAD

**Issue by dnoesgaard** [gbif/portal16#238] opened 2017-01-19 14:05 UTC
There's something odd about the pagination, e.g.

https://demo.gbif.org/cms/search?type=data_use

If you click page 2, nothing happens. Page 3, however, brings up new results, but then page 4 again appears to remain unchanged...

**Comment by MortenHofft** [comment] 2017-01-19 16:25
duplicate of https://github.com/gbif/portal16/issues/233

**Closed by MortenHofft** 2017-01-19 16:25 UTC
