### ISSUE TITLE
Remove envelope to indicate contact information

### ISSUE THREAD

**Issue by peterdesmet** [gbif/portal16#112] opened 2016-10-26 13:15 UTC
It is unclear what the envelope next to a person name is supposed to indicate. See e.g. http://demo.gbif.org/dataset/83e20573-f7dd-4852-9159-21566e1e691e/origin

<img width="974" alt="screen shot 2016-10-26 at 14 58 47" src="https://cloud.githubusercontent.com/assets/600993/19726852/411ad180-9b8d-11e6-8251-ef5b63f8f72b.png">

and 

<img width="919" alt="screen shot 2016-10-26 at 14 59 12" src="https://cloud.githubusercontent.com/assets/600993/19727063/11806330-9b8e-11e6-810a-9276bfab2b64.png">

Is it to indicate
- `contact person`: than the second person (me) should also get that icon, as I'm also a contact person
- `primary contact`: not an EML term, so I guess derived from "first person listed as resource contact"

In the second screenshot, the envelop icon appears twice, with a double meaning: email + contact person.

**Comment by MortenHofft** [comment] 2016-10-26 15:40
Thanks - i like that you notice that. Tt was intended to indicate the first person listed as an administrative contact - that is the primary contact. There might be more, but the first listed as such (which might not be the first originator). This was to avoid scenarios with 10 administrative contacts and to adhere to the IPT principle of respecting provided order. We could consider showing them all, but i somehow like showing a single primary assuming they have been listed in that order for a reason. The others are still available of course and marked as contacts. I see what you mean with the doubly use of the icon. It is a bit odd.

**Comment by MortenHofft** [comment] 2016-11-15 11:06
it still appears in the header next to the first person listed as an administrative contact.

in the full name+address it still appears next to the mail address. But it has been removed next to the persons name as it weren't inline with the use of the 'institution icon'

I personally think it makes ok sense to direct people to the first person listed as a contact and not mark all people in the header. The information is still available on hover and spelled out elsewhere on the page

**Comment by peterdesmet** [comment] 2016-11-16 08:52
Yes, seems fine to use it as such, although I don't think the email addresses in the full contact info need an envelope icon.

**Comment by MortenHofft** [comment] 2017-06-21 17:41
Gone it is. and much has changed. Hopefully to the better. Orcids are now there. Thanks

**Closed by MortenHofft** 2017-06-21 17:41 UTC
Labels: cost low, dataset, impact low, usability

**Comment by MortenHofft** [comment] 2017-06-21 17:43
ahh - just notice that it doesn't anchor as well as it should.
