### ISSUE TITLE
language selector

### ISSUE THREAD

**Issue by dnoesgaard** [gbif/portal16#361] opened 2017-07-04 08:01 UTC
We set content language based on browser setting, but I think we should have an option for people to choose language directly on the site.

**Comment by MortenHofft** [comment] 2017-07-04 12:58
languages are set by prefixing with 2 letter iso code . /es/species/256 and will be available from language selector once we actually have things translated.

For the home page we select some content based on browser settings  - this is an exception and decided by management to do that for the home page already now (before the whole site is translated).

So the plan is to make translations explicit in the url and selectable. like on http://ssg.gbif-uat.org/ar/

I'm closing this as duplicate of https://github.com/gbif/portal16/issues/362 for now.

**Closed by MortenHofft** 2017-07-04 12:58 UTC
