### ISSUE TITLE
taxonKey filter on checklists out of order?

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal16#230] opened 2017-01-17 12:21 UTC
**taxonKey filter on checklists out of order?**

We searched for taxonKey=1355948 and found it should be in 14 checklists. When clicking the link alle checklists are displayed and not only the 14 which contains taxon 1355948

-----
fbitem-0059f96b33a12ae38a9a2449c0865b3a3cdfe76c
Reported by: @NHMD
System: Chrome 55.0.2883 / Mac OS X 10.10.2
Referer: https://demo.gbif.org/dataset/search?type=CHECKLIST&amp;taxonKey=1355948
Window size: width 1835 - height 1065
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-01-17T10:42:13.313Z',mode:absolute,to:'2017-01-17T10:48:13.313Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-01-17T10:42:13.313Z',mode:absolute,to:'2017-01-17T10:48:13.313Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by MortenHofft** [comment] 2017-01-17 12:21
Thank you for reporting @NHMD

How did you end up with that url?
It is intended to be: https://demo.gbif.org/dataset/search?type=CHECKLIST&taxon_key=1355948
Using the interface I haven't been able to reproduce the error

I don't have any preference on underscore vs camel case, but at the time of implementation the general opinion at the office seemed to be underscores. It is a bit confusing though as the API documentation states camelCase (but supports both). The site of course do not have to align to the same parameter naming and it isn't at this point.

**Comment by NHMD** [comment] 2017-01-17 14:47
I ended up on the url by clicking the link to the 12 checklist datasets containing the species on this page: https://demo.gbif.org/species/1353364
Just under the text "Dataset coverage".

**Comment by MortenHofft** [comment] 2017-01-17 15:34
Thank you
Odd - i thought i just tried that, but I now see that it is wrong. I have released a new version. Notice that we still have issues with cache busting https://github.com/gbif/portal16/issues/27 so you might need to do a hard refresh to get the new version. closed by https://github.com/gbif/portal16/commit/3169e3ac7f4ddfb0ef3100f31b6359d22c5ff529

**Closed by MortenHofft** 2017-01-17 15:34 UTC
Labels: bug, search
